//Initiate the api call

const GET_BUDGET_PLANS = 'GET_BUDGET_PLANS',
    GET_BUDGET_PLANS_SUCCESS = 'GET_BUDGET_PLANS_SUCCESS',
    GET_BUDGET_PLANS_FAILED = 'GET_BUDGET_PLANS_FAILED',
    ADD_BUDGET_PLAN = 'ADD_BUDGET_PLAN',
    ADD_BUDGET_PLAN_SUCCESS = 'ADD_BUDGET_PLAN_SUCCESS',
    ADD_BUDGET_PLAN_FAILED = 'ADD_BUDGET_PLAN_FAILED',
    UPDATE_BUDGET_PLAN = 'UPDATE_BUDGET_PLAN',
    UPDATE_BUDGET_PLAN_SUCCESS = 'UPDATE_BUDGET_PLAN_SUCCESS',
    UPDATE_BUDGET_PLAN_FAILED = 'UPDATE_BUDGET_PLAN_FAILED',
    REMOVE_BUDGET_PLAN = 'REMOVE_BUDGET_PLAN',
    REMOVE_BUDGET_PLAN_SUCCESS = 'REMOVE_BUDGET_PLAN_SUCCESS',
    REMOVE_BUDGET_PLAN_FAILED = 'REMOVE_BUDGET_PLAN_FAILED';



export default {
    GET_BUDGET_PLANS, GET_BUDGET_PLANS_SUCCESS, GET_BUDGET_PLANS_FAILED,
    ADD_BUDGET_PLAN, ADD_BUDGET_PLAN_SUCCESS, ADD_BUDGET_PLAN_FAILED,
    UPDATE_BUDGET_PLAN, UPDATE_BUDGET_PLAN_SUCCESS, UPDATE_BUDGET_PLAN_FAILED,
    REMOVE_BUDGET_PLAN, REMOVE_BUDGET_PLAN_SUCCESS, REMOVE_BUDGET_PLAN_FAILED
};