//Initiate the api call

const GET_TRANSACTIONS = 'GET_TRANSACTIONS',
    GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS',
    GET_TRANSACTIONS_FAILED = 'GET_TRANSACTIONS_FAILED',
    ADD_TRANSACTION = 'ADD_TRANSACTION',
    ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS',
    ADD_TRANSACTION_FAILED = 'ADD_TRANSACTION_FAILED',
    UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
    UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS',
    UPDATE_TRANSACTION_FAILED = 'UPDATE_TRANSACTION_FAILED',
    REMOVE_TRANSACTION = 'REMOVE_TRANSACTION',
    REMOVE_TRANSACTION_SUCCESS = 'REMOVE_TRANSACTION_SUCCESS',
    REMOVE_TRANSACTION_FAILED = 'REMOVE_TRANSACTION_FAILED';



export default {
    GET_TRANSACTIONS, GET_TRANSACTIONS_SUCCESS, GET_TRANSACTIONS_FAILED,
    ADD_TRANSACTION, ADD_TRANSACTION_SUCCESS, ADD_TRANSACTION_FAILED,
    UPDATE_TRANSACTION, UPDATE_TRANSACTION_SUCCESS, UPDATE_TRANSACTION_FAILED,
    REMOVE_TRANSACTION, REMOVE_TRANSACTION_SUCCESS, REMOVE_TRANSACTION_FAILED
};